# Generated by Django 3.0.5 on 2020-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200407_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Questions', to='app.Tag', verbose_name='Question tags'),
        ),
    ]
