# Generated by Django 3.0.5 on 2020-04-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200407_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='Questions_dislikes', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Questions_likes', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
