# Generated by Django 3.0.5 on 2020-04-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200407_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/iguana.png', upload_to='static/img/avatars'),
        ),
    ]
